common: &common
  adapter: mysql2
  encoding: utf8
  username: <%=ENV['OPENSHIFT_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_DB_PASSWORD']%>
  host: <%=ENV['OPENSHIFT_DB_HOST']%>
  port: <%=ENV['OPENSHIFT_DB_PORT']%>
  socket: <%=ENV['OPENSHIFT_DB_SOCKET']%>

production:
  <<: *common
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  pool: 5
