common: &common
  adapter: mysql2
  encoding: utf8
  username: root
  password: 
  host: localhost

development:
  <<: *common
  database: note_dev

test:
  <<: *common
  database: note_test

production:
  <<: *common
  database: note_product
