require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectsController do

  before(:each) do 
    @user = Factory(:user)
    @task1 = Factory(:task, :user => @user)
    @task1.project_list = 'proj1'
    @task1.save
    @task2 = Factory(:task, :user => @user, :content => Factory.next(:content))
    @task2.project_list = 'proj2'
    @task2.status = Task::DONE
    @task2.save
    sign_in @user
  end

  # This should return the minimal set of attributes required to create a valid
  # Project. As you add validations to Project, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all projects as @projects" do
      projects = Task.project_counts
      get :index, {}
      assigns(:projects).should eq(projects)
    end
  end

  describe "GET show" do
    it "assigns the requested project as @project" do
      projects = Task.project_counts
      get :show, {:id => 'proj1'}
      assigns(:projects).should eq(projects)
      assigns(:project_name).should eq('proj1')
    end
  end

  describe "GET history" do
    it "assigns the requested tasks are DONE tasks" do
      pending "add some examples to (or delete) #{__FILE__}"
    end
  end

  describe "GET knowledgebase" do
    it "assigns the requested knowledgebase of the project" do
      pending "add some examples to (or delete) #{__FILE__}"
    end
  end

  describe "GET edit" do
    it "assigns the requested project as @project" do
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Project" do
        expect {
          post :create, {:project => { :name => 'proj1' } }
        }.to change(Task, :count).by(1)
      end

      it "redirects to the created project" do
        post :create, {:project => { :name => 'proj1' } }
        response.should redirect_to(projects_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project as @project" do
        # Trigger the behavior that occurs when invalid params are submitted
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project" do
    end

    it "redirects to the projects list" do
    end
  end

end
